#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

# NOTES:
# DO NOT change any folder structure in the "Image Processing" folder
# TESTED WITH: PNG, JPG, BMP

# Libraries
from PIL import Image, ExifTags
import os, traceback

# Parameters
resolution = 256, 256
file_path = os.path.realpath(__file__ + "/../" + "/test-images/")
picture_name = "sunset1.jpg"

print(file_path) # testprint

try:
    test_img = Image.open(file_path + "/" + picture_name)
    if hasattr(test_img, '_getexif'):
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break
        e = test_img._getexif() # Returns NONE if no EXIF data
        if e is not None:
            exif = dict(e.items())
            orientation = exif[orientation]

            if orientation == 3:
                test_img = test_img.transpose(Image.ROTATE_180)
            elif orientation == 6:
                test_img = test_img.transpose(Image.ROTATE_270)
            elif orientation == 8:
                test_img = test_img.transpose(Image.ROTATE_90)

    test_img.resize(resolution).show()

except:
    traceback.print_exc()
